# Generated by Django 3.2.9 on 2021-11-18 17:18

from django.db import migrations, models
import shopping_cart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='shopping_cart/images', validators=[shopping_cart.validators.validate_file_size]),
        ),
    ]
